In [89]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [90]:
df=pd.read_excel("online retail.xlsx")

In [91]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [92]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,525461.000000,525461,525461.000000,417534.000000
mean,10.337667,2010-06-28 11:37:36.845017856,4.688834,15360.645478
min,-9600.000000,2009-12-01 07:45:00,-53594.360000,12346.000000
25%,1.000000,2010-03-21 12:20:00,1.250000,13983.000000
50%,3.000000,2010-07-06 09:51:00,2.100000,15311.000000
75%,10.000000,2010-10-15 12:45:00,4.210000,16799.000000
max,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000
std,107.424110,NaN,146.126914,1680.811316

In [93]:
df.shape

(525461, 8)

In [94]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [95]:
# Remove missing Customer ID
#df = df.dropna(subset=['Customer ID'])

# Fill missing Description
#df['Description'] = df['Description'].fillna("Unknown")

In [96]:
df = df.dropna(subset=['Customer ID'])
df = df[(df['Quantity'] > 0) & (df['Price'] > 0)]

In [97]:
df.shape

(407664, 8)

In [98]:
df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [99]:
df['Sales'] = df['Quantity'] * df['Price']

In [100]:
import numpy as np

df['Discount'] = np.random.uniform(0, 0.3, len(df))

In [101]:
df['Final_Price'] = df['Price'] * (1 - df['Discount'])
df['Sales'] = df['Quantity'] * df['Final_Price']

In [102]:
df['Cost'] = df['Sales'] * (0.8 + df['Discount'])

In [103]:
df['Profit'] = df['Sales'] - df['Cost']

In [104]:
df['Profit_Margin'] = df['Profit'] / df['Sales']

In [105]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month

In [106]:
df['Loss_Flag'] = (df['Profit'] < 0).astype(int)

In [107]:
df['Customer_Spend'] = df.groupby('Customer ID')['Sales'].transform('sum')

In [108]:
df['Product_Profit'] = df.groupby('StockCode')['Profit'].transform('sum')

In [109]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Sales,Discount,Final_Price,Cost,Profit,Profit_Margin,Year,Month,Loss_Flag,Customer_Spend,Product_Profit
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,59.793463,0.283052,4.982789,64.759430,-4.965967,-0.083052,2009,12,1,1737.5229,487.167344
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,78.132085,0.035406,6.511007,65.272041,12.860044,0.164594,2009,12,0,1737.5229,557.687203
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,64.973924,0.197853,5.414494,64.834411,0.139513,0.002147,2009,12,0,1737.5229,829.137956
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,95.873823,0.048871,1.997371,81.384489,14.489334,0.151129,2009,12,0,1737.5229,348.663017
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,26.746543,0.108449,1.114439,24.297859,2.448685,0.091551,2009,12,0,1737.5229,1392.082377

In [110]:
df.isnull().sum()

Invoice           0
StockCode         0
Description       0
Quantity          0
InvoiceDate       0
Price             0
Customer ID       0
Country           0
Sales             0
Discount          0
Final_Price       0
Cost              0
Profit            0
Profit_Margin     0
Year              0
Month             0
Loss_Flag         0
Customer_Spend    0
Product_Profit    0
dtype: int64

In [111]:
df.to_csv("final_dataset.csv", index=False)

In [112]:
# Imports
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
from sqlalchemy import create_engine



# 2. Create MySQL Engine

engine = create_engine(
      "mysql+pymysql://sales_profit:Nikhil%40123@localhost:3306/profit_sales_db"
)



# 3. Read CSV File
data = pd.read_csv("final_dataset.csv")

# 4. Load Data into MySQL
data.to_sql(
    name="sales_data",        
    con=engine,
    if_exists="replace", 
    index=False          
)


print("✅ CSV successfully loaded into MySQL table 'profit_sales_db'")

✅ CSV successfully loaded into MySQL table 'profit_sales_db'

In [113]:
query = """
SELECT 
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit
FROM sales_data;
"""
data = pd.read_sql(query, engine)
print(data)

    Total_Sales   Total_Profit
0  7.514447e+06  447743.447604

In [114]:
query="""SELECT 
    AVG(Profit_Margin) AS Avg_Profit_Margin
FROM sales_data;"""
data = pd.read_sql(query,engine)
print(data)

   Avg_Profit_Margin
0            0.04989

In [115]:
query="""SELECT 
    Year,
    Month,
    SUM(Sales) AS Sales,
    SUM(Profit) AS Profit
FROM sales_data
GROUP BY Year, Month
ORDER BY Year, Month;"""
data = pd.read_sql(query,engine)
print(data)

    Year  Month          Sales        Profit
0   2009     12  584929.345159  35398.440052
1   2010      1  475195.003702  29068.192054
2   2010      2  430543.294098  25454.830055
3   2010      3  596300.338120  36643.791271
4   2010      4  505079.742446  29271.236837
5   2010      5  509431.965512  29511.597554
6   2010      6  542582.188463  31299.663209
7   2010      7  502383.325765  29095.552281
8   2010      8  513891.242340  30650.793982
9   2010      9  705651.761083  40483.795559
10  2010     10  884442.411137  54771.286386
11  2010     11  997881.042768  59683.246595
12  2010     12  266134.979343  16411.021767

In [116]:
query="""SELECT 
    Year, Month,
    SUM(Sales) AS Total_Sales
FROM sales_data
GROUP BY Year, Month
ORDER BY Total_Sales DESC;"""
data=pd.read_sql(query,engine)
print(data)

    Year  Month    Total_Sales
0   2010     11  997881.042768
1   2010     10  884442.411137
2   2010      9  705651.761083
3   2010      3  596300.338120
4   2009     12  584929.345159
5   2010      6  542582.188463
6   2010      8  513891.242340
7   2010      5  509431.965512
8   2010      4  505079.742446
9   2010      7  502383.325765
10  2010      1  475195.003702
11  2010      2  430543.294098
12  2010     12  266134.979343

In [117]:
query="""SELECT 
    StockCode,
    SUM(Sales) AS Total_Sales
FROM sales_data
GROUP BY StockCode
ORDER BY Total_Sales DESC
LIMIT 10;"""
data=pd.read_sql(query,engine)
print(data)

  StockCode    Total_Sales
0    85123A  129112.250803
1     22423  124301.696697
2         M   83817.758699
3    85099B   73227.130743
4     84879   59885.361282
5      POST   41792.048331
6     21843   35883.765333
7     84347   34999.485318
8     48138   34581.866205
9     22086   31545.368134

In [118]:
query="""SELECT 
    StockCode,
    SUM(Profit) AS Total_Profit
FROM sales_data
GROUP BY StockCode
ORDER BY Total_Profit DESC
LIMIT 10;"""
data=pd.read_sql(query,engine)
print(data)

  StockCode  Total_Profit
0     22423   8953.100727
1    85123A   7824.609527
2         M   5168.836313
3    85099B   4842.672532
4     84879   3472.714580
5      POST   2761.494978
6     84347   2629.846154
7     21843   2439.978401
8     22086   2005.334579
9     20685   1927.023192

In [119]:
query="""SELECT 
    SUM(Profit) AS Total_Loss
FROM sales_data
WHERE Profit < 0;"""
data=pd.read_sql(query,engine)
print(data)

      Total_Loss
0 -106682.462872

In [120]:
query = """
SELECT 
    COUNT(*) * 100.0 / (SELECT COUNT(*) FROM sales_data) AS Loss_Percentage
FROM sales_data
WHERE Loss_Flag = 1;
"""
data = pd.read_sql(query, engine)
print(data)

   Loss_Percentage
0         33.31812

In [121]:
query="""SELECT 
    ROUND(Discount,1) AS Discount_Level,
    COUNT(*) AS Transactions,
    AVG(Profit) AS Avg_Profit
FROM sales_data
GROUP BY ROUND(Discount,1)
ORDER BY Discount_Level;"""
data=pd.read_sql(query,engine)
print(data)

   Discount_Level  Transactions  Avg_Profit
0             0.0         67461    3.722800
1             0.1        136348    2.001531
2             0.2        135834    0.022572
3             0.3         68021   -1.166864

In [122]:
query="""SELECT 
    StockCode,
    SUM(Profit) AS Total_Profit
FROM sales_data
GROUP BY StockCode
HAVING SUM(Profit) < 0
ORDER BY Total_Profit ASC;"""
data=pd.read_sql(query,engine)
print(data)

    StockCode  Total_Profit
0       85220   -151.739784
1       22763   -119.712630
2       21984    -61.374420
3      47587A    -45.695825
4       21796    -40.865629
..        ...           ...
215     20881     -0.011983
216     16215     -0.010008
217    35751D     -0.003413
218     84367     -0.002936
219    90004A     -0.000615

[220 rows x 2 columns]

In [123]:
query="""SELECT 
    Country,
    SUM(Profit) AS Total_Profit
FROM sales_data
GROUP BY Country
ORDER BY Total_Profit ASC;"""
data=pd.read_sql(query,engine)
print(data)

                 Country   Total_Profit
0                Nigeria       9.357802
1                 Brazil      13.351640
2                Bahrain      27.898624
3            West Indies      28.998009
4                Iceland      40.836062
5                  Korea      42.566879
6                 Canada      46.153315
7                    RSA      49.432839
8                 Israel     107.424974
9                 Poland     150.176613
10                 Japan     177.638549
11             Singapore     208.437420
12              Thailand     257.702308
13             Lithuania     263.922473
14                   USA     268.214095
15           Unspecified     324.051926
16               Finland     360.364583
17  United Arab Emirates     364.786392
18                 Malta     510.597877
19                Cyprus     579.862775
20                Greece     601.509094
21               Austria     716.687693
22                 Italy     765.299071
23              Portugal     990.300491
24               Belgium    1173.521067
25       Channel Islands    1339.036813
26             Australia    1670.552306
27           Switzerland    2161.144702
28                 Spain    2280.535552
29               Denmark    2365.896007
30                Norway    2565.601185
31                Sweden    2912.173903
32                France    7007.911468
33               Germany    9890.137940
34           Netherlands   13616.837317
35                  EIRE   18601.376020
36        United Kingdom  375253.151821

In [124]:
query="""SELECT 
    ROUND(Discount,1) AS Discount_Level,
    AVG(Profit) AS Avg_Profit
FROM sales_data
GROUP BY ROUND(Discount,1)
ORDER BY Discount_Level;"""
data=pd.read_sql(query,engine)
print(data)

   Discount_Level  Avg_Profit
0             0.0    3.722800
1             0.1    2.001531
2             0.2    0.022572
3             0.3   -1.166864

In [125]:
query="""SELECT 
    SUM(Quantity * Price) AS Sales_Before_Discount,
    SUM(Sales) AS Sales_After_Discount
FROM sales_data;"""
data=pd.read_sql(query,engine)
print(data)

   Sales_Before_Discount  Sales_After_Discount
0           8.832003e+06          7.514447e+06

In [126]:
query="""SELECT 
    StockCode,
    SUM(Sales) AS Sales,
    SUM(Profit) AS Profit
FROM sales_data
GROUP BY StockCode
ORDER BY Sales DESC;"""
data=pd.read_sql(query,engine)
print(data)

     StockCode          Sales       Profit
0       85123A  129112.250803  7824.609527
1        22423  124301.696697  8953.100727
2            M   83817.758699  5168.836313
3       85099B   73227.130743  4842.672532
4        84879   59885.361282  3472.714580
...        ...            ...          ...
4012    79151B       0.361242     0.021710
4013     35930       0.340701     0.032906
4014    84206C       0.311873     0.011511
4015    84205C       0.278215    -0.018878
4016      PADS       0.012418     0.001149

[4017 rows x 3 columns]

In [127]:
import pandas as pd
query="""SELECT 
    SUM(Quantity * Price) AS Sales_Before_Discount,
    
    SUM(Sales) AS Sales_After_Discount,
    
    SUM((Quantity * Price) * 0.4) AS Profit_Before_Discount,
    
    SUM(Profit) AS Profit_After_Discount

FROM sales_data;"""
data=pd.read_sql(query,engine)
print(data)

   Sales_Before_Discount  Sales_After_Discount  Profit_Before_Discount  \
0           8.832003e+06          7.514447e+06            3.532801e+06

   Profit_After_Discount
0          447743.447604

In [128]:
query="""SELECT 
    StockCode,
    SUM(Sales) AS Sales,
    SUM(Profit) AS Profit,
    AVG(Discount) AS Avg_Discount,
    AVG(Profit_Margin) AS Margin
FROM sales_data
GROUP BY StockCode
ORDER BY Sales DESC;"""
data=pd.read_sql(query,engine)
print(data)

     StockCode          Sales       Profit  Avg_Discount    Margin
0       85123A  129112.250803  7824.609527      0.148353  0.051647
1        22423  124301.696697  8953.100727      0.145951  0.054049
2            M   83817.758699  5168.836313      0.151867  0.048133
3       85099B   73227.130743  4842.672532      0.146529  0.053471
4        84879   59885.361282  3472.714580      0.150518  0.049482
...        ...            ...          ...           ...       ...
4012    79151B       0.361242     0.021710      0.139901  0.060099
4013     35930       0.340701     0.032906      0.103417  0.096583
4014    84206C       0.311873     0.011511      0.179282  0.020718
4015    84205C       0.278215    -0.018878      0.267856 -0.067856
4016      PADS       0.012418     0.001149      0.113012  0.086988

[4017 rows x 5 columns]

In [129]:
query="""SELECT 
    StockCode,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit,
    AVG(Profit_Margin) AS Avg_Margin
FROM sales_data
GROUP BY StockCode
HAVING AVG(Profit_Margin) < 0
ORDER BY Avg_Margin ASC;"""
data=pd.read_sql(query,engine)
print(data)

    StockCode  Total_Sales  Total_Profit  Avg_Margin
0      37477C    15.814500     -1.536115   -0.097133
1       20858     4.648592     -0.444721   -0.095668
2       35837     1.198658     -0.113761   -0.094907
3       20715   301.066226    -27.077338   -0.089938
4      90038C    18.849106     -1.543367   -0.081002
..        ...          ...           ...         ...
145    90036B    80.928302     -0.773338   -0.000224
146    90004A     2.999231     -0.000615   -0.000205
147    90035C   226.586465      2.551557   -0.000090
148     20991   653.621330    -19.112335   -0.000010
149    35271S    71.816807      4.779452   -0.000007

[150 rows x 4 columns]

In [131]:
query="""SELECT 
    StockCode,
    SUM(Sales) AS Sales,
    SUM(Profit) AS Profit,
    
    CASE 
        WHEN SUM(Profit) < 0 AND SUM(Sales) > 100 THEN 'Fix Pricing'
        WHEN SUM(Profit) < 0 AND SUM(Sales) <= 100 THEN 'Remove'
        ELSE 'Keep'
    END AS Action

FROM sales_data
GROUP BY StockCode
HAVING SUM(Profit) < 0;"""
data=pd.read_sql(query,engine)
print(data)
data.head(221)

    StockCode        Sales     Profit       Action
0      90209A   127.583274  -0.223408  Fix Pricing
1       72783    38.575293  -1.167022       Remove
2      72801E   315.229980  -2.458730  Fix Pricing
3       35995     2.560464  -0.080029       Remove
4       21732  2512.837183 -31.505578  Fix Pricing
..        ...          ...        ...          ...
215     22858    10.115080  -0.340837       Remove
216    37477C    15.814500  -1.536115       Remove
217     22930   153.653896  -3.725172  Fix Pricing
218     22935   180.000189  -1.367828  Fix Pricing
219     22933    27.239712  -0.831264       Remove

[220 rows x 4 columns]

    StockCode        Sales     Profit       Action
0      90209A   127.583274  -0.223408  Fix Pricing
1       72783    38.575293  -1.167022       Remove
2      72801E   315.229980  -2.458730  Fix Pricing
3       35995     2.560464  -0.080029       Remove
4       21732  2512.837183 -31.505578  Fix Pricing
..        ...          ...        ...          ...
215     22858    10.115080  -0.340837       Remove
216    37477C    15.814500  -1.536115       Remove
217     22930   153.653896  -3.725172  Fix Pricing
218     22935   180.000189  -1.367828  Fix Pricing
219     22933    27.239712  -0.831264       Remove

[220 rows x 4 columns]

In [ ]:
query=""""""
data=pd.read_sql(query,engine)
print(data)

In [ ]:
query=""""""
data=pd.read_sql(query,engine)
print(data)

In [ ]:
query=""""""
data=pd.read_sql(query,engine)
print(data)

In [ ]:
query=""""""
data=pd.read_sql(query,engine)
print(data)